---
title: "Group 4 - Salary Prediction"
author: "Akash Gobalarajah, Cyril Alain Scheurmann, Keijo Alexander Nierula, Roman Krass"
date: "2024.03.14
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE, echo=FALSE}
# Getting started by changing the default output of echo to TRUE for the current document 
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)

# Create a list of packages to install and load into the work space
libraries = c("readr", "tidyverse", "dlookr", "ggplot2", "xgboost", "dplyr")
 
# Install packages from the predefined libraries list
lapply(libraries, function(x) if (!(x %in% installed.packages())) {
  install.packages(x)
})

# Load libraries
lapply(libraries, library, quietly = TRUE, character.only = TRUE)

# Remove current environment 
rm(list=ls())
```

```{r importData}
# Set seed
set.seed(7)

# Importing data
load("data_wage.RData")
salaryData <- data

```

```{r scructure}

# Check the structure of the data
summary(data)
str(data)

```
